### PR TITLE
Added code to handle Warp Connector

### PR DESCRIPTION
**Pull request by vinothsubramanian**
Though WARP Connector is still in beta, the connection works perfectly when connected to a team. 

I have updated entrypoint.sh to skip ```warp-cli registration``` if mdm.xml is present

### CODE REVIEW

**Comment by cmj2002** [comment]
1. The `[Note]` should be `[!NOTE]` so that it can be displayed as a [alert](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) (or callout).
2. You are using prettier or something similar, which changed my ordered list in build instructions. This should be revert.
3. If the mdm file presents, the lisence key should not be registered. 
4. Is the `--accept-tos` necessary? I have done it when starting daemon in line 19.

**Comment by vinothsubramanian** [comment]
@cmj2002 I have fixed the comments. Kindly see below:

1.  Fixed
2. Since it was appearing as continuous numbers I updated it. Now I understood that we need indentation. I have added extra space to take care of it

      _Before Change_
      image
      
      _After Change_
      image

3. Since I don't have active WARP+ I couldn't check it. Moved license key registration inside if block.
4.  Without --accept-tos flag the container fails to start with mdm.xml in place
```
warp-socks  | Please accept the WARP Terms of Service by running this command in a TTY or by passing the --accept-tos flag.
warp-socks  | 2024-08-05T04:04:57.027Z  INFO warp::warp_service::ipc_loop: IPC connection ended
warp-socks exited with code 0
```

**Comment by cmj2002** [comment]
Thanks for the PR! 1

**Comment by cmj2002** [comment]
Docker hub image updated.

**Pull request merged**
