### PR TITLE
Updated README.md for the new token registration command

### PR DESCRIPTION
**Pull request by vinothsubramanian**
Updated the deprecated ```warp-cli teams-enroll-token``` command to ```warp-cli registration token```

### CODE REVIEW

**Comment by cmj2002** [comment]
Is the new command appeared in any document from cloudflare?

**Comment by vinothsubramanian** [comment]
These warnings appear when we execute ```warp-cli``` commands

```
warp@b894cf47e024:/$ warp-cli teams-enroll *****
Warning: The "teams-enroll" command will be deprecated in a future release. Please use "registration initialize-token-callback" instead

A browser window should open at the following URL:

https://*****.cloudflareaccess.com/warp

If the browser fails to open, please visit the URL above directly in your browser.
warp@b894cf47e024:/$ warp-cli teams-enroll-token com.cloudflare.warp://*****.cloudflareaccess.com/auth?token=eyJhbGciOiJSUzI1N***********
Warning: The "teams-enroll-token" command will be deprecated in a future release. Please use "registration token" instead

Success
warp@b894cf47e024:/$

```

**Comment by cmj2002** [comment]
Have you tested the new command? I am on my vacation without my laptop now, so I can't test it. If you have tested it I will merge it.

**Comment by vinothsubramanian** [comment]
Yes I have tested the command and it works

**Pull request merged**
